### ISSUE TITLE
Unable to query by page

### ISSUE THREAD

**Issue by Abdisalan** [Rdbaker/singularity-energy-python-sdk#1]
The SDK only lets you query for the default 300 records in `/v1/region_events/search`. Would be nice to add the page number and page size as a method parameter

**Comment by burkaman** [comment]
With the latest [v0.0.9 release](https://pypi.org/project/singularity-energy/), [`search_region_events`](https://singularity-energy.readthedocs.io/en/latest/full_api.html#singularity.SingularityAPI.search_region_events) and [`search_region_events_for_postal_code`](https://singularity-energy.readthedocs.io/en/latest/full_api.html#singularity.SingularityAPI.search_region_events_for_postal_code) now accept optional `page` and `per_page` parameters.
